### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by Overshakes** [supertuxkart/stk-blender#14]
![image](https://user-images.githubusercontent.com/85829601/134139879-35f8a983-6b25-4e1f-8120-ffd68968031e.png)

When I add a main driveline, lapline and checkline I have this message for export.

Thanks

**Comment by Benau** [comment]
because your track has no ground, add a big square mesh will fix that ![](https://cdn.lihkg.com/assets/faces/pig/sowhat.gif)
![Screenshot from 2021-09-22 11-03-17](https://user-images.githubusercontent.com/3252341/134276928-d3765f39-9b3a-45e2-aadf-8a54349dead1.png)

**Comment by illegalinstruction** [comment]
Hi, I'm still able to reproduce this even after adding a ground plane - is there anything else I can try?

Full stacktrace:

```
Python: Traceback (most recent call last):
  File "/home/redacted/Work/blender/3.6/scripts/addons/io_antarctica_scene/stk_track.py", line 1256, in invoke
    return self.execute(context)
  File "/home/redacted/Work/blender/3.6/scripts/addons/io_antarctica_scene/stk_track.py", line 1270, in execute
    savescene_callback(self, self.filepath, exportImages, self.exportDrivelines, self.exportScene, self.exportMaterials)
  File "/home/redacted/Work/blender/3.6/scripts/addons/io_antarctica_scene/stk_track.py", line 1199, in savescene_callback
    TrackExport(self, sFilePath, exportImages, exportDrivelines and stk_utils.getSceneProperty(bpy.data.scenes[0], 'is_stk_node', 'false') != 'true', exportScene, exportMaterials)
  File "/home/redacted/Work/blender/3.6/scripts/addons/io_antarctica_scene/stk_track.py", line 1169, in __init__
    bpy.ops.screen.spm_export(localsp=False, filepath=sPath+"/"+sTrackName, selection_type="selected", \
  File "/home/redacted/Work/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/redacted/Work/blender/3.6/scripts/addons/io_scene_spm/__init__.py", line 115, in execute
    export_spm.writeSPMFile(self.filepath, spm_parameters)
  File "/home/redacted/Work/blender/3.6/scripts/addons/io_scene_spm/export_spm.py", line 691, in writeSPMFile
    assert len(all_triangles) > 0
AssertionError
Location: /home/redacted/Work/blender/3.6/scripts/modules/bpy/ops.py:113
```

Relevant lines from `system-info.txt`:

**Blender version:** 3.6.14, branch: blender-v3.6-release, commit date: 2024-07-15 09:00, hash: e480a2c4465b, type: Release
**Build date:** 2024-07-15, 10:30:14
**Platform:** 'Linux-5.15.0-134-generic-x86_64-with-glibc2.35'
